### ISSUE TITLE
No error when multiple SYMMETRIC_PARTITION env have the same partition ID

### ISSUE THREAD

**Issue by richardnorth3** [jhrobichaux/SOS#1]
When exporting multiple SHMEM | SYMMETRIC_PARTITION environment variables with the same partition ID, there is no output to stderr. Example below: 

-------------------------------------------------------------------------------------------------
export SMA_DEBUG=foo

export SHMEM_SYMMETRIC_PARTITION20=size=128M:pgsize=4K
export SMA_SYMMETRIC_PARTITION20=size=64M:pgsize=4K
oshrun -np 1 ./hello

Debug: shmem_internal_parse_partition_env
Debug: SHMEM_SYMMETRIC_PARTIION = SMA_SYMMETRIC_PARTITION20=size=64M:pgsize=4K
Partition ID         : 20
        Partition Kind       : 0
        Partition Policy     : 0
        Partition Page Size  : 4096
        Partition Size       : 67108864
        Partition Start Addr : (nil)
        Partition Mspace     : (nil)

Debug: shmem_internal_parse_partition_env
Debug: SHMEM_SYMMETRIC_PARTIION = SHMEM_SYMMETRIC_PARTITION20=size=128M:pgsize=4K
Partition ID         : 20
        Partition Kind       : 0
        Partition Policy     : 0
        Partition Page Size  : 4096
        Partition Size       : 134217728
        Partition Start Addr : (nil)
        Partition Mspace     : (nil)

Hello World from 0 of 1

-------------------------------------------------------------------------------------------
Also, if environment variables with the same partition ID all begin with SHMEM or SMA, the output to the console will only display values for one of those partitions.

**Comment by jhrobichaux** [comment]
Should catch error in commit 303cb27d5e8128b03333737c04d6fc2680eb4334. 

Error output below.

Debug: shmem_internal_parse_partition_env
Debug: SHMEM_SYMMETRIC_PARTIION = SHMEM_SYMMETRIC_PARTITION20=size=128M:pgsize=4K
Partition ID         : 20
        Partition Kind       : 0
        Partition Policy     : 0
        Partition Page Size  : 4096
        Partition File Desc  : 0
        Partition Size       : 134217728
        Partition Size Alloc : 0
        Partition Start Addr : (nil)
        Partition Mspace     : (nil)
Debug: shmem_internal_parse_partition_env
Debug: SHMEM_SYMMETRIC_PARTIION = SMA_SYMMETRIC_PARTITION20=size=64M:pgsize=4K
Partition ID         : 20
        Partition Kind       : 0
        Partition Policy     : 0
        Partition Page Size  : 4096
        Partition File Desc  : 0
        Partition Size       : 67108864
        Partition Size Alloc : 0
        Partition Start Addr : (nil)
        Partition Mspace     : (nil)
Debug: shmem_internal_defined_partitions : 2
Debug: Partition # : 1
Partition ID         : 20
        Partition Kind       : 0
        Partition Policy     : 0
        Partition Page Size  : 4096
        Partition File Desc  : 0
        Partition Size       : 134217728
        Partition Size Alloc : 0
        Partition Start Addr : (nil)
        Partition Mspace     : (nil)
Debug: Partition # : 2
Partition ID         : 20
        Partition Kind       : 0
        Partition Policy     : 0
        Partition Page Size  : 4096
        Partition File Desc  : 0
        Partition Size       : 67108864
        Partition Size Alloc : 0
        Partition Start Addr : (nil)
        Partition Mspace     : (nil)
**ERROR: Partition #1 must be defined.
ERROR: Multiple partitions defined for partition id 20.
[000] ERROR: Processing environment variables for symmetric heap failed: 1**

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 1688 RUNNING AT ubuntu
=   EXIT CODE: 134
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Aborted (signal 6)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions

**Comment by jhrobichaux** [comment]
Closing
