### ISSUE TITLE
Default values are not displayed if SYMMETRIC_PARTITION is not defined and SMA_DEBUG is set

### ISSUE THREAD

**Issue by richardnorth3** [jhrobichaux/SOS#2]
When the SYMMETRIC_PARTITION environment variable is not defined, default values are assigned but when the SMA_DEBUG environment variable is set, there is no output to the console of these values. 

-----------------------------------------------------------------------------------------------------------
export SMA_DEBUG=foo
oshrun -np 1 ./hello

Hello World from 0 of 1

**Comment by jhrobichaux** [comment]
Should be fixed in commit 303cb27d5e8128b03333737c04d6fc2680eb4334


+ export SMA_DEBUG=foo
+ SMA_DEBUG=foo
+ oshrun -np 1 ./hello
Debug: shmem_internal_defined_partitions : 1
Debug: Partition # : 1
Partition ID         : 1
        Partition Kind       : 0
        Partition Policy     : 0
        Partition Page Size  : 4096
        Partition File Desc  : 0
        Partition Size       : 536870912
        Partition Size Alloc : 0
        Partition Start Addr : (nil)
        Partition Mspace     : (nil)
Hello World from 0 of 1
