### ISSUE TITLE
No output to stderr when both SYMMETRIC_PARTITION and SYMMETRIC_SIZE are manually defined

### ISSUE THREAD

**Issue by richardnorth3** [jhrobichaux/SOS#3]
When defining both SYMMETRIC_PARTITION and SYMMETRIC_SIZE, there is no error displayed at runtime.

-------------------------------------------------------------------------------------------------------------
export SMA_DEBUG=foo
export SMA_SYMMETRIC_SIZE=3
export SMA_SYMMETRIC_PARTITION20=size=64M:pgsize=4K
oshrun -np 1 ./hello

Debug: shmem_internal_parse_partition_env
Debug: SHMEM_SYMMETRIC_PARTIION = SMA_SYMMETRIC_PARTITION20=size=64M:pgsize=4K
Partition ID         : 20
        Partition Kind       : 0
        Partition Policy     : 0
        Partition Page Size  : 4096
        Partition Size       : 67108864
        Partition Start Addr : (nil)
        Partition Mspace     : (nil)

Hello World from 0 of 1

**Comment by jhrobichaux** [comment]
Works in commit 303cb27d5e8128b03333737c04d6fc2680eb4334
